version: '3.7'
services:
  db:
    image: postgres:12-alpine
    ports:
      - 5433:5432
    env_file:
      zoo_backend/.env
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
  web:
    build:
      context: zoo_backend
      dockerfile: Dockerfile
    volumes:
      - ./zoo_backend/:/app
    ports:
      - 8000:8000
    depends_on:
      - db
    env_file:
      - zoo_backend/.env
