# Generated by Django 4.1.2 on 2022-10-31 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zoo', '0003_faq_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='country',
        ),
    ]
