# Generated by Django 4.1.2 on 2022-10-31 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zoo', '0004_remove_animal_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='animals', to='zoo.country'),
        ),
    ]
